# Generated by Django 5.0.4 on 2024-04-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.CharField(max_length=200)),
                ('Permit_Number', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=200)),
                ('Building_Name', models.CharField(max_length=200)),
                ('Project_Name', models.CharField(max_length=200)),
                ('Property_Size_Sqft', models.CharField(max_length=200)),
                ('Property_Size_Sqm', models.CharField(max_length=200)),
                ('RoomsBaths', models.CharField(max_length=200)),
                ('Year_of_Completion', models.CharField(max_length=200)),
                ('Built_up_Area_Sqft', models.CharField(max_length=200)),
                ('Property_Type_En', models.CharField(max_length=200)),
                ('Asking_Price_AED', models.CharField(max_length=200)),
                ('REF', models.CharField(max_length=200)),
                ('Instance_Date', models.CharField(max_length=200)),
                ('Actual_Worth_AED', models.CharField(max_length=200)),
                ('Trans_Group', models.CharField(max_length=200)),
                ('Rent_Expiry', models.CharField(max_length=200)),
                ('RentedAgency_1', models.CharField(max_length=200)),
                ('Expiry_Date_1', models.CharField(max_length=200)),
                ('Agency_2', models.CharField(max_length=200)),
                ('Expiry_Date_2', models.CharField(max_length=200)),
                ('Agency_3', models.CharField(max_length=200)),
                ('Expiry_Date_3', models.CharField(max_length=200)),
                ('Count_Buy', models.CharField(max_length=200)),
                ('Count_Rent_Listing_Number', models.CharField(max_length=200)),
                ('Name_En', models.CharField(max_length=200)),
                ('Mobile', models.CharField(max_length=200)),
                ('Unit_Number', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
            ],
        ),
    ]
