# Generated by Django 5.0.4 on 2024-04-23 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='RoomsBaths',
            new_name='Baths',
        ),
        migrations.AddField(
            model_name='property',
            name='Rooms',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
